config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :phonenumber, :email, :company_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field form-group ">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control', placeholder:"first_name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control', placeholder:"last_name"  %>
  </div>

  <div class="field form-group">
    <%= form.label :phonenumber %>
    <%= form.text_field :phonenumber, class: 'form-control', placeholder:"phonenumber"  %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' , placeholder:"email"  %>
  </div>

  <div class="field form-group">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, class: 'form-control', placeholder:"company_name"  %>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>
<br/>

<%= render 'form', client: @client %>
<br/>

<%= link_to 'Show', @client, class: 'btn btn-dark' %> 
<%= link_to 'Back', clients_path , class: 'btn btn-primary' %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients List</h1>

<table class="table table-dark table-striped table-bordered table-hover">
  <thead class = "thead-light">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.phonenumber %></td>
        <td><%= client.email %></td>
        <td><%= client.company_name %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path, class: "btn btn-dark" %>

app/views/clients/new.html.erb
<h1>Add New Client</h1>

<%= render 'form', client: @client %>

<br/>

<%= link_to 'Back', clients_path , class: 'btn btn-secondary' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
  <%= @client.first_name %>
  <%= @client.last_name %>
  </h1>
  <p class="lead"><%= @client.phonenumber %></p>
  <hr class="my-4">
  <p><%= @client.email %></p>
  <hr class="my-4">
  <h1 class="display-4">
  <%= @client.company_name %>
  </h1>
  <p class="lead">
  <%= link_to 'Edit', edit_client_path(@client), class: 'btn btn-secondary' %> 
  <%= link_to 'Back', clients_path, class:'btn btn-dark'  %>
  </p>
</div>
 

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Client Database', root_path, class: 'navbar-brand'  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About', home_about_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item">
      <%= link_to 'Clients', clients_path, class: 'nav-link'  %>
      </li>
     
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Add Client', new_client_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete ,class: 'nav-link'  %>
        </li>
        <li class="nav-item">
        <%= link_to 'Edit Profile',  edit_user_registration_path ,class: 'nav-link'  %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'Sign Up',  new_user_registration_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In',  new_user_session_path, class: 'nav-link'  %>
        </li>
      <% end %> 

    
     
      
 
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Client Database</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Clients Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %>
   <div class= "container">
   <br/>
   <% if notice %>
    <%= render 'layouts/alerts' %>
    <% end %>

   
   <%= yield %>
   </div>
 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>